# Generated by Django 4.1.4 on 2022-12-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_description_alter_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default="DEFAULT VALUE", max_length=255),
        ),
    ]
