# Generated by Django 4.1.4 on 2022-12-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
    ]
