# Generated by Django 4.1.4 on 2022-12-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
