# Generated by Django 4.1.4 on 2022-12-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assigned",
            new_name="assignee",
        ),
    ]
